[project]
name = "credit-risk-analyzer"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Yashvanth742", email = "yashvanthsavanur@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.142.2",
    "joblib>=1.5.2",
    "pandas>=2.3.3",
    "scikit-learn>=1.6.1,<1.7",
    "uvicorn>=0.54.0",
    "xgboost==2.1.4",
]

[project.scripts]
credit-risk-analyzer = "credit_risk_analyzer:main"

[build-system]
requires = ["uv_build>=0.12.4,<0.13.0"]
build-backend = "uv_build"
